name: "vmd-action"
description:
  "A static code analysis tool for detecting code smells and best practice
  violations in Vue.js and Nuxt.js projects."
branding:
  icon: "code"
  color: "green"
inputs:
  github-token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is
      configured with the local git config, which enables your scripts to run
      authenticated git commands. The post-job step removes the PAT.

      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.

      [Learn more about creating and using encrypted
      secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
  version:
    description: >
      Version of Vue Mess Detector to use. This can be a specific version number
      or 'latest' to use the most recent version available.
    required: true
    default: "latest"
  skipInstall:
    description: >
      If set to 'true', the action will skip the installation of Vue Mess Detector.
      This can be useful if Vue Mess Detector is already installed in your environment.
    required: true
    default: "false"
  skipBots:
    description: >
      If set to 'true', the action will skip running analysis on pull requests
      created by bots. This can help reduce unnecessary analysis runs.
    required: true
    default: "true"
  commentsEnabled:
    description: >
      If set to 'true', the action will post comments on pull requests with the
      results of the analysis. If set to 'false', no comments will be posted.
    required: true
    default: "true"
  packageManager:
    description: >
      The package manager to use for installing dependencies. Supported values
      are 'npm', 'yarn', 'pnpm', and 'bun'. If not specified, the action will
      attempt to detect the package manager based on the lock file present in
      the repository.
    required: false
  runArgs:
    description: >
      Additional arguments to pass to Vue Mess Detector when running the analysis.
      This can be used to customize the behavior of the analysis.
    default: "--group=file"
    required: false
  entryPoint:
    description: >
      The entry point for Vue Mess Detector. This is the directory where the
      analysis will start. If not specified, the current directory will be used.
    required: false
  srcDir:
    description: >
      The source directory to analyze. This should be the path to the directory
      containing the source code you want to analyze. If not specified, 'src/'
      will be used.
    required: true
    default: "src/"
  deleteOldComments:
    description: >
      If set to 'true', the action will delete old comments on pull requests
      before posting new ones. This can help keep the comment section clean.
    required: false
    default: "false"
  relativeMode:
    description: >
      If set to 'true', the action will generate a report comparing the current
      branch with the target branch. This can be useful for identifying changes
      introduced in a pull request.
    required: true
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
